// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

error DoctorIsDead();
error DoctorHasAlreadyBrewed();
error PotionsNotEnough(uint256 potionsLeft);
error InvalidDifficulty();
error VrfResponseNotReceived();
error VrfResponsePending();
error InvalidVrfRequestId();
error InvalidStartTime();
error BrewNotStarted();
error BrewHasStarted();
error DoctorAlreadyClaimed();
error ClaimNotStarted();
error InvalidDoctorIdsLength();
error GameEnded();
error DoctorNotOwnedBySender();
error DoctorNotDead();
error DoctorAlreadyBrewed();
error NoPotionLeft();

error InvalidPlayerNumberToEndGame();
error InvalidInfectionPercentage();
error InvalidEpochDuration();
error TooManyInitialized();
error InvalidCollection();
error GameAlreadyStarted();
error GameNotStarted();
error GameNotOver();
error GameIsClosed();
error InfectionNotComputed();
error NothingToCompute();
error EpochNotReadyToEnd();
error EpochAlreadyEnded();
error DoctorNotInfected();
error UpdateToSameStatus();
error InvalidRequestId();
error VRFResponseMissing();
error VRFRequestAlreadyAsked();
error CantAddPrizeIfGameIsOver();
error NotAWinner();
error WithdrawalClosed();
error FundsTransferFailed();
